# Generated by Django 5.2.6 on 2025-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brithday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
