# Generated by Django 5.2.6 on 2025-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0002_alter_user_brithday_alter_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
