# Generated by Django 5.2.6 on 2025-09-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0004_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatedEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('education_type', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('diploma_number', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='residential_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
