# Generated by Django 5.2.6 on 2025-09-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0005_graduatededucation_residential_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatededucation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GraduatedEducation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residential_address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
