# Generated by Django 5.2.6 on 2025-09-29 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0007_alter_graduatededucation_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('winter', 'Qish'), ('summer', 'Yoz')], max_length=10)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('selfimg', models.ImageField(upload_to='admissions/selfimg/')),
                ('certificate_of_general_secondary_education', models.FileField(upload_to='admissions/certificate/')),
                ('medical_file', models.FileField(upload_to='admissions/medical/')),
                ('passport', models.FileField(upload_to='admissions/passports/')),
                ('visa', models.FileField(upload_to='admissions/visa/')),
                ('photo', models.ImageField(upload_to='admissions/photos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-semester'],
                'unique_together': {('user', 'semester', 'year')},
            },
        ),
    ]
