# Generated by Django 5.2.6 on 2025-09-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0008_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='selfimg',
        ),
    ]
