# Generated by Django 5.2.6 on 2025-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('university_name_uz', models.CharField(max_length=255, null=True)),
                ('university_name_en', models.CharField(max_length=255, null=True)),
                ('university_name_ru', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('country_uz', models.CharField(max_length=255, null=True)),
                ('country_en', models.CharField(max_length=255, null=True)),
                ('country_ru', models.CharField(max_length=255, null=True)),
                ('official_website', models.URLField()),
                ('university_logo', models.ImageField(upload_to='university_logo')),
            ],
        ),
    ]
