# Generated by Django 5.2.6 on 2025-09-20 04:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advancedtraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtraining',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='advancedtraining',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='advancedtraining',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='advancedtraining',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advancedtraining',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advancedtraining',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
