# Generated by Django 5.2.6 on 2025-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedtraining',
            options={'verbose_name': 'Advanced Training', 'verbose_name_plural': 'Advanced Trainings'},
        ),
        migrations.AlterModelOptions(
            name='internationalexchangeprogram',
            options={'verbose_name': 'International Exchange Program', 'verbose_name_plural': 'International Exchange Programs'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterField(
            model_name='trips',
            name='date',
            field=models.DateField(),
        ),
    ]
