# Generated by Django 5.2.6 on 2025-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_advancedtraining_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('official_website', models.URLField()),
                ('university_logo', models.ImageField(upload_to='partner_university_logo/')),
            ],
            options={
                'verbose_name': 'Partner University',
                'verbose_name_plural': 'Partner Universities',
            },
        ),
        migrations.AlterField(
            model_name='internationalexchangeprogram',
            name='university_logo',
            field=models.ImageField(upload_to='university_logo/'),
        ),
    ]
