# Generated by Django 5.2.6 on 2025-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_university',
            name='country_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner_university',
            name='country_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner_university',
            name='country_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner_university',
            name='university_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner_university',
            name='university_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner_university',
            name='university_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
