# Generated by Django 5.2.6 on 2025-09-22 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partner_university_country_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonoraryProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('country_uz', models.CharField(max_length=255, null=True)),
                ('country_en', models.CharField(max_length=255, null=True)),
                ('country_ru', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('img', models.ImageField(upload_to='honorary_professors/')),
            ],
        ),
    ]
