# Generated by Django 5.2.6 on 2025-09-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_honoraryprofessors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honoraryprofessors',
            options={'verbose_name': 'Honorary Professor', 'verbose_name_plural': 'Honorary Professors'},
        ),
    ]
