# Generated by Django 5.2.6 on 2025-09-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_honoraryprofessors_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('country_uz', models.CharField(max_length=255, null=True)),
                ('country_en', models.CharField(max_length=255, null=True)),
                ('country_ru', models.CharField(max_length=255, null=True)),
                ('course', models.CharField(max_length=255)),
                ('course_uz', models.CharField(max_length=255, null=True)),
                ('course_en', models.CharField(max_length=255, null=True)),
                ('course_ru', models.CharField(max_length=255, null=True)),
                ('direction', models.CharField(max_length=255)),
                ('direction_uz', models.CharField(max_length=255, null=True)),
                ('direction_en', models.CharField(max_length=255, null=True)),
                ('direction_ru', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(upload_to='international_students/')),
            ],
            options={
                'verbose_name': 'International Student',
                'verbose_name_plural': 'International Students',
            },
        ),
        migrations.CreateModel(
            name='InternationalStudentsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='international_students_images/')),
                ('international_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.internationalstudents')),
            ],
            options={
                'verbose_name': 'International Student Image',
                'verbose_name_plural': 'International Student Images',
            },
        ),
    ]
