# Generated by Django 5.2.6 on 2025-09-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUzbekistan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('link', models.URLField()),
                ('img', models.ImageField(upload_to='about_uzbekistan/')),
            ],
            options={
                'verbose_name': 'About Uzbekistan',
                'verbose_name_plural': 'About Uzbekistan',
            },
        ),
    ]
