# Generated by Django 5.2.6 on 2025-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutuzbekistan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('e_type', models.CharField(max_length=255)),
                ('e_form', models.CharField(max_length=255)),
                ('e_language', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Educational Area',
                'verbose_name_plural': 'Educational Areas',
            },
        ),
    ]
