# Generated by Django 5.2.6 on 2025-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_educationalareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalareas',
            name='e_form_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_form_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_form_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_language_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_language_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_language_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_type_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='e_type_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
