# Generated by Django 5.2.6 on 2025-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_educationalareas_e_form_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255)),
                ('language_uz', models.CharField(max_length=255, null=True)),
                ('language_en', models.CharField(max_length=255, null=True)),
                ('language_ru', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='brochures/')),
                ('file_uz', models.FileField(null=True, upload_to='brochures/')),
                ('file_en', models.FileField(null=True, upload_to='brochures/')),
                ('file_ru', models.FileField(null=True, upload_to='brochures/')),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
            },
        ),
    ]
