# Generated by Django 5.2.6 on 2025-09-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
