# Generated by Django 5.2.6 on 2025-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='title_uz',
        ),
    ]
