# Generated by Django 5.2.6 on 2025-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_grant_description_en_grant_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='partner_organizations/')),
            ],
            options={
                'verbose_name': 'Partner Organization',
                'verbose_name_plural': 'Partner Organizations',
            },
        ),
    ]
