def get_text(language):
    # 'uz-uz', 'en-us' kabi kodlarni 'uz', 'en' ga qisqartiramiz
    language = language.split('-')[0]

    return {
        'uz': {
            'home': 'Asosiy',
            'welcome': 'Shaxsiy kabinetga xush kelibsiz!',
            'welcome_2': "Andijon Davlat texnika instituti XALQARO HAMKORLIK BO'LIMI WEB-SAHIFASIGA XUSH KELIBSIZ!",
            'contact': "Kontakt",
            'enter_profile': 'Profilga kirish',
            'logout': 'Chiqish',
            'Admission': 'Qabul',
            'Admission_title': 'Oliy va kasb-hunar ta’limi muassasalariga qabul (2024-2025 o‘quv yili uchun)',
            'grants': 'Grantlar',
            'advanced_training': 'Chet elda malaka oshirish va ta’lim',
            'international_exchange': 'Xalqaro almashinuv dasturi',
            'foreign_trips': 'Xorijiy safarlar va tashriflar',
            'partner_universities': 'Xalqaro hamkor Universitetlar',
            'honorary_professors': 'Xalqaro professorlar',
            'international_students': 'Xalqaro talaba',
            'ratings': 'Xalqaro reyting',
            'cabinet': 'Shaxsiy kabinet',
            'educational_areas': 'Ta’lim yo‘nalishlari',
            'about_uzbekistan': 'O‘zbekiston haqida',
            'hotels': 'Xorijiy talabalar uchun yotoqxona',
            'daily_expenses': 'Kunlik xarajatlari',
            'brouchers': 'Broucherlar',
            'news': 'Yangiliklar',
            'more': 'Batafsil',
            'reset_password': 'Parolni tiklash',
            'international_activity': 'Xalqaro faoliyat',
            'international_exchange_program_2': 'Andijon mashinasozlik instituti quyidagi oliygohlar bilan o’zaro talabalar almashinuvi dasturlarini yo’lga qo’ygan',
            'university_name': 'Universitet nomi',
            'country': 'Davlat',
            'official_website': 'Rasmiy sayti',
            'university_logo': 'Universitet logotipi',
            'certificate_of_general_secondary_education': 'Qabul qilish uchun serhit',
            'medical_file': 'Medik file',
            'passport': 'Passport',
            'visa': 'Visa',
            'photo': 'Photo',
        },
        'ru': {
            'home': 'Главная',
            'welcome': 'Добро пожаловать в личный кабинет!',
            'welcome_2': "Добро пожаловать на веб-сайт департамента международной сотрудничества ИНТЭХИ!",
            'contact': "Связаться",
            'enter_profile': 'Войти в профиль',
            'logout': 'Выйти',
            'Admission': 'Прием',
            'Admission_title': 'Прием в высшие учебные заведения (на 2024-2025 учебный год)',
            'grants': 'Доступы',
            'advanced_training': 'Повышение квалификации',
            'international_exchange': 'Международный обмен',
            'foreign_trips': 'Международные поездки',
            'partner_universities': 'Международные университеты',
            'honorary_professors': 'Международные профессора',
            'international_students': 'Международные студенты',
            'ratings': 'Рейтинги',
            'cabinet': 'Личный кабинет',
            'educational_areas': 'Образовательные области',
            'about_uzbekistan': 'О Узбекистане',
            'hotels': 'Отель для иностранцев',
            'daily_expenses': 'Компенсация за проживание',
            'brouchers': 'Брошюры',
            'news': 'Новости',
            'more': 'Подробнее',
            'reset_password': 'Сбросить пароль',
            'international_activity': 'Международная деятельность',
            'international_exchange_program_2': 'Институт иностранных студентов и международных обменов',
            'university_name': 'Институт',
            'country': 'Страна',
            'official_website': 'Официальный сайт',
            'university_logo': 'Логотип университета',
            'certificate_of_general_secondary_education': 'Сертификат о среднем общем образовании',
            'medical_file': 'Медицинская запись',
            'passport': 'Паспорт',
            'visa': 'Виза',
            'photo': 'Фото',
        },
        'en': {
            'home': 'Home',
            'welcome': 'Welcome to your personal cabinet!',
            'welcome_2': "WELCOME TO Andijan State Technical Institute INTERNATIONAL COOPERATION DEPARTMENT WEB PAGE!",
            'contact': "Contact",
            'enter_profile': 'Enter profile',
            'logout': 'Logout',
            'Admission': 'Admission',
            'Admission_title': 'Admission to higher and professional educational institutions (for the 2024-2025 academic year)',
            'grants': 'Grants',
            'advanced_training': 'Advanced training',
            'international_exchange': 'International exchange',
            'foreign_trips': 'Foreign trips',
            'partner_universities': 'Partner universities',
            'honorary_professors': 'Honorary professors',
            'international_students': 'International students',
            'ratings': 'Ratings',
            'cabinet': 'Cabinet',
            'educational_areas': 'Educational areas',
            'about_uzbekistan': 'About Uzbekistan',
            'hotels': 'Hotels for foreign students',
            'daily_expenses': 'Daily expenses',
            'brouchers': 'Brochures',
            'news': 'News',
            'more': 'More',
            'reset_password': 'Reset password',
            'international_activity': 'International activity',
            'international_exchange_program_2': 'Andijon State Technical Institute International Exchange Program',
            'university_name': 'University name',
            'country': 'Country',
            'official_website': 'Official website',
            'university_logo': 'University logo',
            'certificate_of_general_secondary_education': 'Certificate of general secondary education',
            'medical_file': 'Medical file',
            'passport': 'Passport',
            'visa': 'Visa',
            'photo': 'Photo',
        },
    }.get(language, {})

